import { User } from "./manager";

export const DUMMY_USERS: User[] = [
  {
    id: "1",
    name: "이정준",
    role: "driver",
    company: "Microsoft",
    phone: "(225) 555-0118",
    employeeId: "80번 4721",
    location: "서울",
    status: "운행 중",
  },
  {
    id: "2",
    name: "이예지",
    role: "driver",
    company: "Yahoo",
    phone: "(205) 555-0100",
    employeeId: "70번 9234",
    location: "부산",
    status: "휴일",
  },
  {
    id: "3",
    name: "송준혁",
    role: "driver",
    company: "Adobe",
    phone: "(302) 555-0107",
    employeeId: "75번 3561",
    location: "대구",
    status: "휴일",
  },
  {
    id: "4",
    name: "조정훈",
    role: "driver",
    company: "Tesla",
    phone: "(252) 555-0126",
    employeeId: "77번 1892",
    location: "인천",
    status: "운행 중",
  },
  {
    id: "5",
    name: "박건국",
    role: "driver",
    company: "Google",
    phone: "(629) 555-0129",
    employeeId: "82번 7456",
    location: "광주",
    status: "운행 중",
  },
  {
    id: "6",
    name: "정우영",
    role: "driver",
    company: "Microsoft",
    phone: "(406) 555-0120",
    employeeId: "83번 2398",
    location: "대전",
    status: "운행 중",
  },
  {
    id: "7",
    name: "김현지",
    role: "driver",
    company: "Yahoo",
    phone: "(208) 555-0112",
    employeeId: "85번 6743",
    location: "울산",
    status: "운행 중",
  },
  {
    id: "8",
    name: "이도훈",
    role: "driver",
    company: "Facebook",
    phone: "(704) 555-0127",
    employeeId: "87번 5127",
    location: "경기",
    status: "휴일",
  },
];
