import { User } from "./manager";

export const DUMMY_USERS: User[] = [
  {
    id: 1,
    username: "driver1",
    name: "이정준",
    role: "driver",
    phone: "(225) 555-0118",
    employeeId: "80번 4721",
    region: "서울",
    status: "운행 중",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=LeeJungJun&backgroundColor=b6e3f4",
  },
  {
    id: 2,
    username: "driver2",
    name: "이예지",
    role: "driver",
    phone: "(205) 555-0100",
    employeeId: "70번 9234",
    region: "부산",
    status: "휴일",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=LeeYeJi&backgroundColor=c0aede",
  },
  {
    id: 3,
    username: "driver3",
    name: "송준혁",
    role: "driver",
    phone: "(302) 555-0107",
    employeeId: "75번 3561",
    region: "대구",
    status: "휴일",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=SongJunHyeok&backgroundColor=b6e3f4",
  },
  {
    id: 4,
    username: "driver4",
    name: "조정훈",
    role: "driver",
    phone: "(252) 555-0126",
    employeeId: "77번 1892",
    region: "인천",
    status: "운행 중",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=JoJungHun&backgroundColor=c0aede",
  },
  {
    id: 5,
    username: "driver5",
    name: "박건국",
    role: "driver",
    phone: "(629) 555-0129",
    employeeId: "82번 7456",
    region: "광주",
    status: "운행 중",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=ParkGunKuk&backgroundColor=ffd5dc",
  },
  {
    id: 6,
    username: "driver6",
    name: "정우영",
    role: "driver",
    phone: "(406) 555-0120",
    employeeId: "83번 2398",
    region: "대전",
    status: "운행 중",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=JungWooYoung&backgroundColor=b6e3f4",
  },
  {
    id: 7,
    username: "driver7",
    name: "김현지",
    role: "driver",
    phone: "(208) 555-0112",
    employeeId: "85번 6743",
    region: "울산",
    status: "운행 중",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=KimHyunJi&backgroundColor=c0aede",
  },
  {
    id: 8,
    username: "driver8",
    name: "이도훈",
    role: "driver",
    phone: "(704) 555-0127",
    employeeId: "87번 5127",
    region: "경기(수원)",
    status: "휴일",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=LeeDooHoon&backgroundColor=d1d4f9",
  },
  {
    id: 9,
    username: "driver9",
    name: "서정빈",
    role: "driver",
    phone: "(509) 555-0133",
    employeeId: "90번 8234",
    region: "강릉",
    status: "운행 중",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=KangMinSeo&backgroundColor=ffd5dc",
  },
  {
    id: 10,
    username: "driver10",
    name: "김한주",
    role: "driver",
    phone: "(603) 555-0123",
    employeeId: "92번 1459",
    region: "구미",
    status: "휴일",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=ChoiSeoYeon&backgroundColor=b6e3f4",
  },
  {
    id: 11,
    username: "driver11",
    name: "오형남",
    role: "driver",
    phone: "(701) 555-0183",
    employeeId: "95번 3672",
    region: "전주",
    status: "운행 중",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=HanJiWon&backgroundColor=c0aede",
  },
  {
    id: 12,
    username: "driver12",
    name: "박성민",
    role: "driver",
    phone: "(503) 555-0137",
    employeeId: "98번 7890",
    region: "제주",
    status: "휴일",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=ParkSungMin&backgroundColor=d1d4f9",
  },
  {
    id: 13,
    username: "driver13",
    name: "김태호",
    role: "driver",
    phone: "(208) 555-0114",
    employeeId: "99번 4567",
    region: "천안",
    status: "운행 중",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=KimTaeHo&backgroundColor=ffd5dc",
  },
  {
    id: 14,
    username: "driver14",
    name: "윤하진",
    role: "driver",
    phone: "(435) 555-0198",
    employeeId: "100번 2345",
    region: "춘천",
    status: "운행 중",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=YoonHaJin&backgroundColor=b6e3f4",
  },
  {
    id: 15,
    username: "driver15",
    name: "임수진",
    role: "driver",
    phone: "(582) 555-0144",
    employeeId: "102번 6789",
    region: "안동",
    status: "휴일",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=ImSuJin&backgroundColor=c0aede",
  },
  {
    id: 16,
    username: "driver16",
    name: "강동원",
    role: "driver",
    phone: "(582) 555-0155",
    employeeId: "103번 1234",
    region: "포항",
    status: "운행 중",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=KangDongWon&backgroundColor=b6e3f4",
  },
  {
    id: 17,
    username: "driver17",
    name: "한소희",
    role: "driver",
    phone: "(582) 555-0166",
    employeeId: "104번 5678",
    region: "창원",
    status: "휴일",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=HanSoHee&backgroundColor=ffd5dc",
  },
  {
    id: 18,
    username: "driver18",
    name: "장민석",
    role: "driver",
    phone: "(582) 555-0177",
    employeeId: "105번 9012",
    region: "용인",
    status: "운행 중",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=JangMinSeok&backgroundColor=c0aede",
  },
  {
    id: 19,
    username: "driver19",
    name: "정유미",
    role: "driver",
    phone: "(582) 555-0188",
    employeeId: "106번 3456",
    region: "청주",
    status: "운행 중",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=JungYouMi&backgroundColor=d1d4f9",
  },
  {
    id: 20,
    username: "driver20",
    name: "이승훈",
    role: "driver",
    phone: "(582) 555-0199",
    employeeId: "107번 7890",
    region: "김해",
    status: "휴일",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=LeeSeungHoon&backgroundColor=b6e3f4",
  },
  {
    id: 21,
    username: "driver21",
    name: "백지민",
    role: "driver",
    phone: "(582) 555-0200",
    employeeId: "108번 1234",
    region: "경기(성남)",
    status: "운행 중",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=BaekJiMin&backgroundColor=ffd5dc",
  },
  {
    id: 22,
    username: "driver22",
    name: "최우진",
    role: "driver",
    phone: "(582) 555-0211",
    employeeId: "109번 5678",
    region: "서울",
    status: "운행 중",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=ChoiWooJin&backgroundColor=c0aede",
  },
  {
    id: 23,
    username: "driver23",
    name: "김태리",
    role: "driver",
    phone: "(582) 555-0222",
    employeeId: "110번 9012",
    region: "부산",
    status: "휴일",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=KimTaeRi&backgroundColor=d1d4f9",
  },
  {
    id: 24,
    username: "driver24",
    name: "박보검",
    role: "driver",
    phone: "(582) 555-0233",
    employeeId: "111번 3456",
    region: "대구",
    status: "운행 중",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=ParkBoGum&backgroundColor=b6e3f4",
  },
  {
    id: 25,
    username: "driver25",
    name: "송혜교",
    role: "driver",
    phone: "(582) 555-0244",
    employeeId: "112번 7890",
    region: "인천",
    status: "휴일",
    profileImage:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=SongHyeKyo&backgroundColor=ffd5dc",
  },
];
